from __future__ import annotations

import json
from typing import Any

from flamenco_frames.prompting.family_context import build_family_context
from flamenco_frames.schemas.codebook import Codebook


ANNOTATION_OUTPUT_SCHEMA = {
    "unit_id": "string",
    "language": "es | en | unknown",
    "annotations": [
        {
            "family_id": "string",
            "concept_id": "string",
            "decision": "present | absent | uncertain",
            "confidence": "number from 0.0 to 1.0",
            "evidence_span": "exact quote from focal text, or empty string if absent",
            "rationale": "brief explanation grounded in the codebook",
            "boundary_notes": "why this is not confused with neighboring or trap cases",
            "negative_guardrail_checked": "boolean",
        }
    ],
    "rejected_candidates": [
        {
            "family_id": "string",
            "concept_id": "string",
            "reason": "why the candidate was rejected",
        }
    ],
    "needs_human_review": "boolean",
    "human_review_reason": "string",
}


def compact_json(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=2)


def candidate_summary(candidate_row: dict[str, Any]) -> list[dict[str, Any]]:
    summary = []

    for candidate in candidate_row.get("candidates", []):
        summary.append(
            {
                "family_id": candidate.get("family_id"),
                "concept_id": candidate.get("concept_id"),
                "score": candidate.get("score"),
                "sources": candidate.get("sources", []),
                "regex_hits": candidate.get("regex_hits", []),
                "bm25_hits": [
                    {
                        "doc_id": hit.get("doc_id"),
                        "doc_type": hit.get("doc_type"),
                        "language": hit.get("language"),
                        "score": hit.get("score"),
                        "contribution": hit.get("contribution"),
                        "metadata": {
                            "excerpt": (hit.get("metadata") or {}).get("excerpt"),
                            "rationale": (hit.get("metadata") or {}).get("rationale"),
                            "is_good_example": (hit.get("metadata") or {}).get("is_good_example"),
                            "is_borderline": (hit.get("metadata") or {}).get("is_borderline"),
                            "example_type": (hit.get("metadata") or {}).get("example_type"),
                        },
                    }
                    for hit in candidate.get("bm25_hits", [])
                ],
            }
        )

    return summary


def build_annotation_prompt(
    *,
    codebook: Codebook,
    candidate_row: dict[str, Any],
    language: str = "es",
    include_all_sibling_concepts: bool = True,
    max_examples_per_concept: int = 3,
) -> str:
    family_context = build_family_context(
        codebook=codebook,
        candidate_row=candidate_row,
        include_all_sibling_concepts=include_all_sibling_concepts,
        max_examples_per_concept=max_examples_per_concept,
    )

    unit_payload = {
        "unit_id": candidate_row.get("unit_id"),
        "issue_id": candidate_row.get("issue_id"),
        "article_id": candidate_row.get("article_id"),
        "article_name": candidate_row.get("article_name"),
        "page_number": candidate_row.get("page_number"),
        "logical_page": candidate_row.get("logical_page"),
        "language": language,
        "focal_text": candidate_row.get("text"),
    }

    candidates = candidate_summary(candidate_row)

    return f"""You are annotating historical flamenco periodical text using a strict qualitative codebook.

Your task is NOT to assign every plausible keyword match.
Your task is to decide whether each candidate code is analytically present in the focal text.

Follow these rules:

1. Use the codebook definitions, use_when, and do_not_use_when fields.
2. Treat trap examples as negative guardrails.
3. Do not code a passage only because a trigger word appears.
4. Prefer "absent" when the passage is merely descriptive, administrative, geographic, or generic.
5. Use "uncertain" only when the passage is genuinely borderline.
6. Evidence spans must be exact quotes from the focal text.
7. If a candidate is rejected, explain why.
8. Return valid JSON only. Do not include markdown.

Important methodological note:
The candidate codes were generated by a noisy sparse router. Some candidates are expected to be false positives.

ANNOTATION UNIT:
{compact_json(unit_payload)}

CANDIDATE CODES FROM RETRIEVAL:
{compact_json(candidates)}

CODEBOOK FAMILY CONTEXT:
{compact_json(family_context)}

REQUIRED JSON OUTPUT SHAPE:
{compact_json(ANNOTATION_OUTPUT_SCHEMA)}
"""